---
- name: Create cluster in K3d
  hosts: master01
  become: false

  tasks:
    - name: Remove previous cluster
      shell:
        k3d cluster rm lab-k3d
    - name: Create cluster
      shell:
        k3d cluster create lab-k3d