---
- name: Run NGINX
  hosts: master01
  become: true

  tasks:
    - name: Running nginx with docker
      community.docker.docker_container:
        name: nginx
        image: nginx:1.25
        ports:
          - 8080:80
        detach: true 